import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { CARD_PRODUCTION, DEFAULT_PRODUCTION, productionOf, cardImagePrompt, imageFingerprint, validateVisualCopy } from "../src/lab/gen/production.ts";
import { validateImageRequest, createCardImage, decodePNG } from "../src/lab/gen/imageServer.ts";
import { generateCardImages, generatedImageFiles, imageIsCurrent, type ImageCache } from "../src/lab/render/generatedCards.ts";
import { DEFAULT_BRAND, cardsMessages, type DraftRequest } from "../src/lab/gen/prompt.ts";
import { writeDeck, rewriteDeck } from "../src/lab/gen/pipeline.ts";
import { NEWS, type Card, type Draft } from "../src/lab/data/demo.ts";
import { POST } from "../app/api/card-image/route.ts";

const body="앱은 검색어를 서비스에 보내고 검색 결과를 받습니다. 받은 제목과 링크는 AI에게 참고 자료로 전달됩니다. AI는 이 자료를 참고해 답변을 작성합니다. 검색 자료를 전달하는 단계와 답변을 작성하는 단계가 이어지는 흐름입니다.";
const card:Card={kind:"body",title:"자료가 답변이 되는 과정",body,diagram:{kind:"flow",items:[{label:"검색 요청",detail:"앱이 검색어를 보냅니다"},{label:"결과 전달",detail:"제목과 링크를 받습니다"},{label:"답변 작성",detail:"AI가 자료를 참고합니다"}]},glossary:{term:"API",meaning:"앱이 요청을 보내고 결과를 받는 연결 통로입니다."}};
const cards:Card[]=[{kind:"cover",title:"AI도 검색하고 답한다",body:"앱에 웹 검색을 연결하는 방식을 살펴봅니다."},...Array.from({length:5},(_,i)=>({...card,title:card.title+" "+i})),{kind:"outro",title:"세 가지 핵심",body:"검색 결과를 참고 자료로 전달합니다. AI가 자료를 참고해 답변을 작성합니다.",diagram:{kind:"checklist",items:[{label:"검색 연결"},{label:"결과 전달"},{label:"답변 작성"}]}}];
const draft:Draft={id:"generated-test",createdAt:1,type:"심층",engine:"groq",status:"검토 대기",sources:[],deck:{cards,caption:"요약",hashtags:["#AI"]},blog:{title:"",intro:"",sections:[],outro:"",tags:[]}};
const request:DraftRequest={type:"심층",items:[NEWS[0]],brand:DEFAULT_BRAND,prompts:{},cardFormatVersion:1};
const written=await writeDeck(async()=>draft.deck,request);
assert.deepEqual(written.cards[2].diagram,card.diagram);
assert.deepEqual(written.cards[2].glossary,card.glossary);
assert.equal(written.cards[6].diagram?.items.length,3);
await assert.rejects(()=>writeDeck(async()=>({...draft.deck,cards:cards.map((c,i)=>i===2?{...c,diagram:undefined}:c)}),request),/3장.*도식/);
await assert.rejects(()=>rewriteDeck(async()=>({...draft.deck,cards:cards.map((c,i)=>i===2?{...c,glossary:undefined}:c)}),request,draft.deck,"쉽게"),/3장.*용어/);
assert.equal(productionOf({}).mode,"generated","Existing cloud settings without the new field receive the approved default");
assert.equal(productionOf({production:{mode:"template"}}).mode,"template");
assert.ok(cardsMessages(request)[0].content.includes("설명·도식 균형"));
const prompt=cardImagePrompt(card,3,7,DEFAULT_PRODUCTION);
assert.ok(prompt.includes(body)&&prompt.includes("검색 요청")&&prompt.includes("연결 통로"));
assert.ok(prompt.includes("03 | 발바닥 아이콘 | @otterlab.ai"));
assert.notEqual(imageFingerprint(card,3,7,DEFAULT_PRODUCTION),imageFingerprint(card,4,7,DEFAULT_PRODUCTION),"Page move invalidates footer");
assert.notEqual(imageFingerprint(card,3,7,DEFAULT_PRODUCTION),imageFingerprint({...card,glossary:{term:"API",meaning:"수정한 뜻"}},3,7,DEFAULT_PRODUCTION));
assert.throws(()=>validateVisualCopy({...card,diagram:{kind:"flow",items:[{label:"하나"}]}},3),/도식/);
assert.throws(()=>validateImageRequest({card,page:3,total:2,production:DEFAULT_PRODUCTION}),/페이지/);
assert.throws(()=>validateImageRequest({card:{...card,body:"너무 짧은 설명"},page:3,total:7,production:DEFAULT_PRODUCTION}),/90~260/);
assert.throws(()=>validateImageRequest({card:{...card,sections:{}},page:3,total:7,production:DEFAULT_PRODUCTION}),/추가 설명/);

const png=(await readFile("public/card-style/approved-explainer.png")).toString("base64");
const result=decodePNG(png);
assert.equal(result.width,1254);assert.equal(result.width,result.height);
assert.throws(()=>decodePNG(Buffer.from("<html>no image</html>").toString("base64")),/PNG/);
const wrong=Buffer.from(png,"base64");wrong.writeUInt32BE(1000,20);
assert.throws(()=>decodePNG(wrong.toString("base64")),/정사각형/);

const cacheMap=new Map<string,Blob>();
const cache:ImageCache={read:async id=>cacheMap.get(id),save:async(id,blob)=>{cacheMap.set(id,blob);}};
const done:number[]=[];let calls=0;
await assert.rejects(()=>generateCardImages(draft,DEFAULT_BRAND,{cache,generate:async(_card,page)=>{calls++;if(page===4)throw new Error("서비스 일시 중단");return result;},onImage:(i,image)=>{draft.deck.cards[i]={...draft.deck.cards[i],image};done.push(i+1);}}),/일시 중단/);
assert.deepEqual(done,[1,2,3]);assert.equal(calls,4);
await assert.rejects(()=>generatedImageFiles(draft,DEFAULT_BRAND,"test",undefined,cache),/4장.*먼저/);
calls=0;
await generateCardImages(draft,DEFAULT_BRAND,{cache,generate:async()=>{calls++;return result;},onImage:(i,image)=>{draft.deck.cards[i]={...draft.deck.cards[i],image};}});
assert.equal(calls,4,"Retry resumes remaining pages and does not charge for valid cached pages");
const first=draft.deck.cards[0].image;
const files=await generatedImageFiles(draft,DEFAULT_BRAND,"test",undefined,cache);
assert.equal(files.length,7);assert.equal(files[0].name,"test-01.png");
assert.deepEqual(Buffer.from(await files[2].arrayBuffer()),Buffer.from(png,"base64"),"Export preserves the approved generated bytes");
draft.deck.cards[2]={...draft.deck.cards[2],body:body+" 문구 수정입니다."};
assert.equal(imageIsCurrent(draft.deck.cards[2],3,7,DEFAULT_PRODUCTION),false);
await assert.rejects(()=>generatedImageFiles(draft,DEFAULT_BRAND,"test",undefined,cache),/3장.*먼저/);
calls=0;await generateCardImages(draft,DEFAULT_BRAND,{cache,generate:async()=>{calls++;return result;},onImage:(i,image)=>{draft.deck.cards[i]={...draft.deck.cards[i],image};}});
assert.equal(calls,1);assert.strictEqual(draft.deck.cards[0].image,first);
cacheMap.delete(draft.deck.cards[4].image!.id);
await assert.rejects(()=>generatedImageFiles(draft,DEFAULT_BRAND,"test",undefined,cache),/5장.*브라우저/);

const names=["OPENAI_API_KEY","OPENAI_IMAGE_MODEL","OPENAI_IMAGE_QUALITY","NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY","NEXT_PUBLIC_SUPABASE_ANON_KEY"];
const before=Object.fromEntries(names.map(n=>[n,process.env[n]]));
try {
  for(const name of names)delete process.env[name];
  assert.equal((await POST(new Request("http://localhost/api/card-image",{method:"POST",body:"{}"}))).status,501);
  process.env.OPENAI_API_KEY="test-key-placeholder";
  const payload=validateImageRequest({card,page:3,total:7,production:DEFAULT_PRODUCTION});
  let paidRequests=0;
  const generated=await createCardImage(payload,async(url,init)=>{
    paidRequests++;assert.equal(url,"https://api.openai.com/v1/images/edits");
    assert.equal(new Headers(init?.headers).get("authorization"),"Bearer test-key-placeholder");
    const form=init!.body as FormData;
    assert.equal(form.get("model"),"gpt-image-1");assert.equal(form.get("size"),"1024x1024");assert.equal(form.get("n"),"1");
    assert.equal(form.get("quality"),"high");assert.equal(form.get("response_format"),null);
    const refs=form.getAll("image[]") as File[];assert.equal(refs.length,2);
    assert.deepEqual(Buffer.from(await refs[1].arrayBuffer()),Buffer.from(png,"base64"));
    assert.ok(String(form.get("prompt")).includes(card.title));
    return Response.json({data:[{b64_json:png}]});
  });
  assert.equal(paidRequests,1);assert.deepEqual(generated,result);
  assert.equal((await POST(new Request("http://localhost/api/card-image",{method:"POST",body:"null"}))).status,400);
  assert.equal((await POST(new Request("http://localhost/api/card-image",{method:"POST",body:"x".repeat(16001)}))).status,400);
  await assert.rejects(()=>createCardImage(payload,async()=>Response.json({error:{message:"provider private detail"}},{status:429})),e=>e instanceof Error&&e.message.includes("한도")&&!e.message.includes("private detail"));
  process.env.NEXT_PUBLIC_SUPABASE_URL="https://example.supabase.co";process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="sb_publishable_test";
  assert.equal((await POST(new Request("http://localhost/api/card-image",{method:"POST",body:JSON.stringify(payload)}))).status,401,"Owner guard runs before a paid image request");
} finally {for(const name of names){if(before[name]===undefined)delete process.env[name];else process.env[name]=before[name];}}
console.log("CARD PRODUCTION OK: balanced copy, immutable references, provider contract, partial retry, stale-image rejection, exact export, missing key, owner authentication");
