import assert from 'node:assert/strict';
import { captionWithSources, selectHashtags, SIGN_OFF, finalizeDeck } from '../src/lab/gen/editorial.ts';
import { NEWS } from '../src/lab/data/demo.ts';
import { DEFAULT_BRAND, designOf } from '../src/lab/gen/prompt.ts';
import { normalizeDeck } from '../src/lab/gen/normalize.ts';
const items = [NEWS[0], NEWS[0], {...NEWS[1], link:'javascript:alert(1)'}];
const cap = captionWithSources('새로운 소식을 정리했어요. #태그 https://invented.example', items);
assert.equal(cap.split(NEWS[0].link).length - 1, 1);
assert.equal(cap.split(SIGN_OFF).length - 1, 1);
assert.ok(!cap.includes('invented.example') && !cap.includes('javascript:') && !cap.includes('#태그'));
assert.equal(captionWithSources(cap, items), cap);
assert.equal(selectHashtags(['#AI', '#ai', '#', '#기술', '#뉴스', '#연구', '#개발', '#추가'], items).length,5);
assert.equal(selectHashtags([], []).length,5);
assert.equal(designOf({...DEFAULT_BRAND, design:{...designOf(DEFAULT_BRAND),size:'portrait'}}).size,'square');
const deck = finalizeDeck({cards:[],caption:'요약',hashtags:[]},items);
const structured = {kind:'body',title:'설명',body:'요약',sections:[{heading:'배경',body:'원문에서 확인한 배경'}]};
const normalized = normalizeDeck({cards:[{kind:'cover',title:'제목',body:'소개'},structured,{kind:'outro',title:'정리',body:'핵심'}]},deck);
assert.deepEqual(normalized.cards[1].sections, structured.sections);
console.log('EDITORIAL OK: source allowlist, deduplication, stable caption, five tags, square legacy design, editable explanation blocks');
const { CARD_TEMPLATES, chooseCardTemplate } = await import('../src/lab/data/cardTemplates.ts');
const { writingOf, cardsMessages } = await import('../src/lab/gen/prompt.ts');
const { templateDeck } = await import('../src/lab/gen/template.ts');
assert.equal(writingOf(DEFAULT_BRAND).deepCards + 2,7);
assert.equal(writingOf(DEFAULT_BRAND).bundleCount + 2,7);
assert.equal(templateDeck('심층',[NEWS[0]],DEFAULT_BRAND).cards.length,7);
assert.equal(CARD_TEMPLATES.length,10);
assert.equal(new Set(CARD_TEMPLATES.map(t=>t.id)).size,10);
assert.equal(chooseCardTemplate({kind:'cover',title:'표지',body:'소개'},1),'main');
assert.equal(chooseCardTemplate({kind:'outro',title:'정리',body:'핵심'},7),'courier');
assert.equal(chooseCardTemplate({kind:'body',title:'성능 비교',body:'결과'},3),'analyst');
assert.equal(chooseCardTemplate({kind:'body',title:'서비스의 한계',body:'제약'},6),'caution');
assert.equal(chooseCardTemplate({kind:'body',title:'배경',body:'내용',template:'dialogue'},2),'dialogue');
const scenes=Array.from({length:5},(_,i)=>chooseCardTemplate({kind:'body',title:'소식',body:'내용'},i+2));
assert.equal(new Set(scenes).size,5,'Seven-card fallback uses five different body scenes');
const custom=normalizeDeck({cards:[{kind:'cover',title:'표지',body:'소개'}, {...structured,template:'checklist'}, {kind:'outro',title:'정리',body:'핵심'}]},deck);
assert.equal(custom.cards[1].template,'checklist');
assert.equal(finalizeDeck(custom,items).cards[1].template,'checklist');
assert.ok(cardsMessages({type:'심층',items:[NEWS[0]],brand:DEFAULT_BRAND,prompts:{}})[0].content.includes('dialogue='));
console.log('TEMPLATES OK: seven-card defaults, ten roles, semantic selection, varied fallbacks, manual choice preservation');

assert.equal(chooseCardTemplate({kind:'cover',title:'표지',body:'소개',template:'courier'},1),'main','Old explicit cover choices cannot override main mascot');
assert.equal(chooseCardTemplate({kind:'body',title:'설명',body:'내용',template:'dialogue'},1),'main','Moving a body card to first page keeps main mascot fixed');
assert.notEqual(chooseCardTemplate({kind:'body',title:'설명',body:'내용',template:'main'},2),'main','Main remains exclusive to the first page');
assert.equal(finalizeDeck({...deck,cards:[{kind:'cover',title:'표지',body:'소개',template:'analyst'}]},items).cards[0].template,'main');
console.log('MAIN COVER OK: fixed first-page mascot, legacy overrides ignored, body choices preserved');
